### ISSUE TITLE
Ergo wallet balance is not updated in version 4.0.9

### ISSUE THREAD

**Issue by geodiegofer** [ErgoWallet/ergowallet-desktop#10]
Yesterday I made a purchase of a few ergo and wanted to put them in my wallet. The transaction was made by the exchange, I can see the value in my wallet address, but I can't see the ergo value in my own wallet installed on my computer. Anyone can help me to solve this problem?

**Comment by geodiegofer** [comment]
I have to clarify that the problem is using the Ergo node interface.

**Comment by gagarin55** [comment]
Hello!

Thank you for report. It's better to ask Ergo Full Node developers directly - https://github.com/ergoplatform/ergo/issues
