### ISSUE TITLE
cannot see ergo in my address

### ISSUE THREAD

**Issue by renfengyi2020** [ErgoWallet/ergowallet-desktop#43]
Dear Sir/Madam,

I cannot see the balance of my ergo in the ergo wallet. I remembered my 12 words correctly and entered the wallet. However, I cannot see the ergo balance(how much ERG it has). Could you please help me solve this? Thank you.

**Comment by gagarin55** [comment]
Please, try new release https://github.com/ErgoWallet/ergowallet-desktop/releases/tag/v0.1.12
