### ISSUE TITLE
there are coins in my wallet

### ISSUE THREAD

**Issue by rotcepsni74** [ErgoWallet/ergowallet-desktop#45]
Hello, help me, there are coins in my wallet, but how can I get to them, they are at the change address, they were available a year ago. I Installed different versions Ergo Nod from github  found out that there is an error and its fix with the mnemonic phrase when restoring the wallet but it didn't help me
![Снимок](https://github.com/ErgoWallet/ergowallet-desktop/assets/142964964/444d250a-d34b-45d5-a978-c8ef4ce3efa5)
![Снимок1](https://github.com/ErgoWallet/ergowallet-desktop/assets/142964964/92766af3-47ea-4122-8f5a-64b6b699e406)
![photo_2023-08-22_10-38-00](https://github.com/ErgoWallet/ergowallet-desktop/assets/142964964/75746696-d533-47b4-b9f1-36d1f45598c0)

**Comment by gagarin55** [comment]
New release during the week will fix it. What is your OS ?

**Comment by rotcepsni74** [comment]
Thank you very much, all the coins have appeared in the wallet, don’t change anything else, otherwise it’s scary to transfer, but in the mobile version of the wallet, to see the same changes?
![Снимок2](https://github.com/ErgoWallet/ergowallet-desktop/assets/142964964/f056ba85-8a60-4f9d-96c4-e5446772f070)

**Comment by gagarin55** [comment]
Mobile wallet doesn't support **change** addresses. You had better transfer your change to **receiving** address.

**Comment by rotcepsni74** [comment]
Okay, thanks, I'll do that
