### ISSUE TITLE
Unable to Deposit ERG Tokens to Desktop Wallet

### ISSUE THREAD

**Issue by Zen1313** [ErgoWallet/ergowallet-desktop#6]
I am not a programmer in any way, I signed up to GitHub because I was forced to in order to send a message through the Ergo desktop wallet I downloaded at https://ergowallet.io The Windows version ergo-wallet-win-0.1.10    
I have created a wallet name, password, & have 12 word recovery phrase. Usually when I download a wallet, see the icon installed on my desktop, and open the wallet through that icon, I am able to safely deposit & send tokens; at this point that is all I am looking for (to get my ERG tokens off the exchange I bought them on & store them safely. I can see the addresses and they say clean, I am unable to copy and past them, the history tab just keeps spinning, am I missing something here, do I have to be a programmer to use this desktop wallet version. I have downloaded many desktop wallets (especially in the early days of crypto), this wallet does not seem to be functioning to me, any help to get my tokens off the exchange and into this wallet would be greatly appreciated. Thank you.      --- Jess

**Comment by gagarin55** [comment]
Thank you for your report. We are working to improve UI/UX of Ergo Wallet. 

1. First of all save your 12 word phrase in a safe place to be able to recover wallet in the future
2. You can deposit ERG onto the first address from the **ADDRESSES** tab
3. Select first address with a mouse and use `Ctrl+C` to copy it in clipboard and then use `Ctrl+V` to paste 
4. Try to deposit a small amount of ERG at first time, just to be sure that all work properly

**Comment by Zen1313** [comment]
Yuri, thank you very much for the prompt response & the supplied information, looking for a fantastic future for the team at Ergo. Congratulations to the team are in order for teaming up with the BEAST known as Cardano!!!    — Jess
