### ISSUE TITLE
Ergo token balance not showing in new download version for windows?

### ISSUE THREAD

**Issue by Zen1313** [ErgoWallet/ergowallet-desktop#7]
Downloaded the newest version 0.1.11 for windows, selected import wallet and used my seed phrase to access. Token balance from old version wallet are not showing in new updated download. How do I get my token balance to show the correct amount in new wallet? Thank you.  

   --- Jess R Kumher

**Comment by gagarin55** [comment]
Hello, 

1. Can you see your addresses? Are they the same as before?

2. Did you use wallet password in previous version ?

**Comment by Zen1313** [comment]
Yuri, my addresses in the new wallet version are not the same as the original one I created. I downloaded new version 0.1.11 then selected import wallet & used my previously created wallet information. Same wallet name, password, and 12 word seed phrase; none of my tokens are showing in the new wallet? I deposited all of my tokens in the first version of the wallet to the same address( again this address is not showing in the new version of the wallet). How do I retrieve tokens?   — Jess

**Comment by gagarin55** [comment]
There was an error in previous version of wallet.
Please, while you import mnemonic phrase tick "BIP39  passphrase" checkbox and input your `wallet password` there.

If success, please, transfer your funds into new mnemonic (without BIP39 passphrase)

**Comment by Vilema76** [comment]
My ergos from pool don't show in balance. Did I lose them?
