### ISSUE TITLE
Transfer ERGO tokens from 0.1.10 version to 0.1.11 version?

### ISSUE THREAD

**Issue by Zen1313** [ErgoWallet/ergowallet-desktop#9]
Unable to move my ERGO tokens from old version to new version. Received directions from previous query, to check use BIP address box when importing existing wallet, my balance did not transfer to new version upon doing  so?  I have sent 1 test tx from old version wallet 9eadA92TbFHYNUuEXn24y3f1TxynvWWaTGFNvuJdTXzyu1EiewK     
 ( this is the address all of my ERGO were received in wallet version 0.1.10). I downloaded new version 0.1.11 and sent a test tx to clean receiving address 9gzcYsbGWFfsSa1cHLmTZujJqBRsXye9jtk3K1GmADMhfQ3rokW from my old version 0.1.10. Tx still not showing for deposit to new address in version 0.1.11?

**Comment by gagarin55** [comment]
Is it your test TX - https://ergoscan.io/tx/44c5aa7029f6d97be28cd01ca491c8994e9418d1c22bdec60a8f4192dc4fcd55 ?

**Comment by Zen1313** [comment]
Yuri, thank you for the prompt response, I was able to transfer all of my Ergo tokens to the newest (1.11.1), this transaction hash you sent went through. Before this tx I sent just 1 Ergo token as a test, it was not showing up, everything good now. When will the ability to log in without having to use seed phrase be available? Congratulations to the team with the Cardano collaboration, HUGE potential for all involved, keep on pushing the envelope!!!     — Jess R Kumher
